
class SaloonShop{
  final String name;
  final int id;
  final String address;
  final String image;
  final String rating;
  final String profession;
  final String description;
  final List<String> employeeNames;
  final List<String> employeeRatings;
  final List<String> employeeImages;
  final List<String> timings;
  final shopIndex;
  final employeeAmount;

  SaloonShop({required this.timings,required this.id,required this.shopIndex,required this.profession,required this.name, required this.address, required this.image, required this.rating, required this.description, required this.employeeNames,
    required this.employeeRatings, required this.employeeImages, required this.employeeAmount
  });
}

var saloonServiceList = [
  {'title': 'Women\s Haircut', 'duration': '45', 'price': '30'},
  {'title': 'Women\s Haircut & Trim', 'duration': '60', 'price': '50'},
  {'title': 'Women Trim', 'duration': '25', 'price': '75'},
];


List<SaloonShop> saloonBestList = [
  SaloonShop(
    id: 10,
    shopIndex: 0,
    profession: "Saloon Employee",
    name: "El Sagheer Salon",
    address: "Salah El-Deen, Zamalek",
    image: "assets/all_images/El_Sagheer.jpg",
    rating: "4.7",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Omar"],
    employeeRatings: ["-","4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/El_Sagheer.jpg","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 11,
    shopIndex: 1,
    profession: "Saloon Employee",
    name: "Ahmed & Abdou Beauty Center",
    address: "Nadi Al Saeed, Dokki",
    description: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    image: "assets/all_images/ahmedandabdou.png",
    rating: "4.3",
    employeeNames: ["Anybody","Ahmed", "Rana", "Ziad"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Ahmed.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 12,
    shopIndex: 2,
    profession: "Saloon Employee",
    name: "Kriss Beauty Salon",
    address: "Aswan sq, Mohandessin",
    image: "assets/all_images/Kriss.PNG",
    rating: "4.9",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Wael", "Laila", "Omar"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Kriss.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 18,
    shopIndex: 3,
    profession: "Saloon Employee",
    name: "Curls by Mohamed Elsoury",
    address: "Sheikh Zayed",
    image: "assets/all_images/Curls.PNG",
    rating: "4.6",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Curls.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
];


List<SaloonShop> saloonList = [
  SaloonShop(
    id: 10,
    shopIndex: 0,
    profession: "Saloon Employee",
    name: "El Sagheer Salon",
    address: "Salah El-Deen, Zamalek",
    image: "assets/all_images/El_Sagheer.jpg",
    rating: "4.7",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Omar"],
    employeeRatings: ["-","4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/El_Sagheer.jpg","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 11,
    shopIndex: 1,
    profession: "Saloon Employee",
    name: "Ahmed & Abdou Beauty Center",
    address: "Nadi Al Saeed, Dokki",
    description: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    image: "assets/all_images/ahmedandabdou.png",
    rating: "4.3",
    employeeNames: ["Anybody","Ahmed", "Rana", "Ziad"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Ahmed.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 12,
    shopIndex: 2,
    profession: "Saloon Employee",
    name: "Kriss Beauty Salon",
    address: "Aswan sq, Mohandessin",
    image: "assets/all_images/Kriss.PNG",
    rating: "4.9",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Wael", "Laila", "Omar"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Kriss.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
  SaloonShop(
    id: 18,
    shopIndex: 3,
    profession: "Saloon Employee",
    name: "Curls by Mohamed Elsoury",
    address: "Sheikh Zayed",
    image: "assets/all_images/Curls.PNG",
    rating: "4.6",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Curls.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),SaloonShop(
    id: 19,
    shopIndex: 4,
    profession: "Saloon Employee",
    name: "Toi Beauty Salon",
    address: "90 st, New Cairo",
    image: "assets/all_images/Toi.jpg",
    rating: "4.5",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Toi.jpg","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),SaloonShop(
    id: 20,
    shopIndex: 5,
    profession: "Saloon Employee",
    name: "Rabie Mrad Beauty Lounge",
    address: "River Walk, New Cairo",
    image: "assets/all_images/Rabie.PNG",
    rating: "4.9",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Rabie.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),SaloonShop(
    id: 21,
    shopIndex: 6,
    profession: "Saloon Employee",
    name: "Vine Nail Spa",
    address: "Midtown Mall, New Cairo",
    image: "assets/all_images/Vine.PNG",
    rating: "4.8",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Vine.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),SaloonShop(
    id: 22,
    shopIndex: 7,
    profession: "Saloon Employee",
    name: "Mohamed Gaber",
    address: "Mivida Park, New Cairo",
    image: "assets/all_images/Gaber.jpg",
    rating: "4.5",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Gaber.jpg","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),SaloonShop(
    id: 23,
    shopIndex: 8,
    profession: "Saloon Employee",
    name: "Brush Salon",
    address: "Point 90, New Cairo",
    image: "assets/all_images/Brush.PNG",
    rating: "4.1",
    description: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    employeeNames: ["Anybody","Tamer", "Salma", "Abdullah"],
    employeeRatings: ["4.6", "4.7", "4.8"],
    employeeImages: ["assets/all_images/Brush.PNG","assets/all_images/male3.png", "assets/all_images/female4.jpg", "assets/all_images/male4.jpeg"],
    employeeAmount: 4,
    timings: [  '9:00', '9:15', '9:30', '9:45', '10:00', '10:15', '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '12:00',],
  ),
];